name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm version "$VERSION"
      - run: git config push.followTags true
      - run: git push
      - run: gh release create "v$VERSION"
